### ISSUE TITLE
Can it displays a list of contact based on search criteria ? (and how)

### ISSUE THREAD

**Issue by jbonlinea** [agileware/wp-civicrm-ux#2]
Hi,
I'm digging into your module and wondre if it is readymade to display a list of contact (like a directory) based on seach criteriathat may be defined 1) in the shortcode itself, 2) in a civicrm profile, 3) belonging to certain.s group.s ?

Thank's in advnace for your guidance

**Comment by agileware-justin** [comment]
@jbonlinea good question! We use https://github.com/agileware/content-views-civicrm-data-processor for contact directories.

This plugin is useful for doing things like setting up a member area, member profile page where you want to display specific contact fields and membership type, status on the page.

A contact directory would most likely need to be implemented as a page template, rather than a shortcode due to providing features like search and a pager. But again this is really replicating what can be achieved using the content-views-civicrm-data-processor plugin.

**Comment by jbonlinea** [comment]
Hi 
Thank's for your reply, I get the point indeed, that's not where I'm heading at the moment but it's something that might follow soon, and your plug-in migh definitly be useful then.

I'll dig the data processor approach and see then !

Thank's
